# Generated by Django 3.1.7 on 2021-03-26 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2021, 3, 26, 18, 36, 34, 699642, tzinfo=utc))),
            ],
        ),
    ]
