# Generated by Django 3.1.7 on 2021-03-26 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210327_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 19, 11, 53, 545978, tzinfo=utc)),
        ),
    ]
