# Generated by Django 3.1.7 on 2021-03-31 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210331_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 7, 16, 36, 265935, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='profile_pic/default.png', upload_to=users.models.image_path),
        ),
    ]
